### ISSUE TITLE
Issue with WWW 2.4.5 on Linux

### ISSUE THREAD

**Issue by Bobbicat** [jimbob88/wheelers-wort-works#32]
I have installed a copy of Kubuntu 19.04 beta on a partition in my pc.
[I don't think this is an OS bug]
I attempted to install a fresh WWW from scratch on it and discovered a bug.
As this is a.deb file I used QApt to install.

I installed the latest WWW 2.4.5. 
Unfortunately it seems the installation is not creating a .config/WWW file so errors are being thrown up.
I am reporting this from Kubuntu18.10, I didn't have my gthub details handy on 19.04.

I will get back on the other version when I am able.
I have posted the feedback below.

**Comment by Bobbicat** [comment]
$ sudo apt install wheelers-wort-works

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
wheelers-wort-works is already the newest version (2.4.5).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

```
---

$ sudo wheelers-wort-works --coreupdate

```
Updating beer_engine.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine.py
Updating beer_engine2.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/beer_engine2.py
Updating brew_data.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/brew_data.py
Updating main.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/main.py
Updating update.py from https://raw.githubusercontent.com/jimbob88/wheelers-wort-works/master/update.py
Traceback (most recent call last):
  File "/usr/include/wheelers-wort-works/main.py", line 104, in <module>
    with open(resource_path(u'commit.txt'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '~/.config/Wheelers-Wort-Works/commit.txt'

```
---

~$ wheelers-wort-works
```
Traceback (most recent call last):
  File "/usr/include/wheelers-wort-works/main.py", line 114, in <module>
    beer_engine.main(update_available=update_available)
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 4224, in main
    gui = beer_engine_mainwin(root)
  File "/usr/include/wheelers-wort-works/beer_engine.py", line 40, in __init__
    with open(resource_path('defaults.txt'), 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bob/.config/Wheelers-Wort-Works/defaults.txt'
```

**Comment by jimbob88** [comment]
This issue has been fixed in the latest deb file, previous version must be purged before installation - sorry about any issues you have encountered

**Comment by Bobbicat** [comment]
I completely removed/purged the operating system Kubuntu1904beta with all its files.
I re-installed the operating system.
I downloaded WWW version 2.4.5.
I installed WWW using QApt (a .deb installer).

No ~/.config/Wheelers-Wort-Works folder is created during install.
Thus all the above errors are reported as before.
The bug is not fixed.
